# -*- coding: utf-8 -*-
"""q2 intensity_transformations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WwH4ryQK7VkUXkHK6VIQSa23nwVJY3Kc
"""

import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

img_orig = cv.imread('a1images/brain_proton_density_slice.png', cv.IMREAD_GRAYSCALE)

t_white = np.zeros(256, dtype='uint8')
t_white[141:181] = np.linspace(141, 180, 40).astype('uint8')

t_gray = np.zeros(256, dtype='uint8')
t_gray[181:221] = np.linspace(181, 220, 40).astype('uint8')

white_matter = cv.LUT(img_orig, t_white)
gray_matter = cv.LUT(img_orig, t_gray)

fig, ax = plt.subplots(2, 2, figsize=(6, 6))
ax[0,0].imshow(white_matter, cmap='gray', vmin=0, vmax=255)
ax[0,0].set_title('White Matter')
ax[0,0].axis('off')
ax[1,0].plot(t_white)
ax[1,0].set_ylim([0, 255])
ax[1,0].set_xlim([0, 255])
ax[0,1].imshow(gray_matter, cmap='gray', vmin=0, vmax=255)
ax[0,1].set_title('Gray Matter')
ax[0,1].axis('off')
ax[1,1].plot(t_gray)
ax[1,1].set_ylim([0, 255])
ax[1,1].set_xlim([0, 255])
plt.tight_layout()
plt.show()

import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

img = cv.imread('a1images/brain_proton_density_slice.png', cv.IMREAD_GRAYSCALE)

if img is None:
    print("Error: Image not loaded. Please check the file path.")
else:
    hist, bins = np.histogram(img.ravel(), 256, [0, 256])
    fig, ax = plt.subplots(1, 2, figsize=(12, 4))
    ax[0].imshow(img, cmap='gray', vmin=0, vmax=255)
    ax[0].set_title('Original Image')
    ax[0].axis('off')
    ax[1].plot(hist)
    ax[1].set_title('Histogram')
    ax[1].set_xlabel('Intensity Value')
    ax[1].set_ylabel('Frequency')
    plt.show()